---
- name: Reconfigure named to use user 'named'
  template: src=default.named.j2 dest=/etc/default/named owner=root group=root mode=0644

- name: Chown named directories
  file: path={{ item }} state=directory owner=named group=named recurse=yes
  with_items:
    - /var/run/named
    - /var/named
    - /var/named/slave
    - /var/named/master

- name: Enable named
  file: path=/etc/rc.d/rc.bind mode=0755

- name: Copy 'update-root-hints' file to server
  copy: src=update-root-hints dest=/etc/cron.monthly owner=root group=root mode=0755
  notify:
    - update-root-hints

- name: Create /etc/named.conf file
  template: src=named.conf.j2 dest=/etc/named.conf owner=root group=root mode=0644 validate='/usr/sbin/named-checkconf %s'
  notify:
    - restart named

- name: Create master zone files
  template: src=named.zone.j2 dest="/var/named/master/{{ item.key }}" owner=named group=named mode=0644 validate='/usr/sbin/named-checkzone {{ item.key }} %s'
  with_dict: "{{ named_zones|default({}) }}"
  when: "item.value.type == 'master'"
  notify:
    - restart named
