---
- name: Install bind
  slackpkg: name=bind state=present

- name: Create 'named' group
  group: name=named gid=53 state=present system=yes

- name: Create 'named' user
  user: name=named group=named uid=53 state=present system=yes home=/var/named shell=/sbin/nologin createhome=no

- name: Reconfigure named to use user 'named'
  template: src=default.named.j2 dest=/etc/default/named owner=root group=root mode=0644

- name: Chown named directories
  file: path={{ item }} state=directory owner=named group=named recurse=yes
  with_items:
    - /var/run/named
    - /var/named

- name: Enable named
  file: path=/etc/rc.d/rc.bind mode=0755

- name: Copy 'update-root-hints' file to server
  copy: src=update-root-hints dest=/etc/cron.monthly owner=root group=root mode=0755
  notify:
    - update-root-hints

- name: Create /etc/named.conf file
  template: src=named.conf.j2 dest=/etc/named.conf owner=root group=root mode=0644 validate='/usr/sbin/named-checkconf %s'
